services:

  monolith:
    build:
      context: ./monolith
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=eshop
      - DB_USER=eshop_user
      - DB_PASSWORD=eshop_password
      - DB_DROP_SCHEMA=true
      - ERP_API_URL=http://erp-api:3200
      - TAX_API_URL=http://tax-api:3201
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=eshop
      - POSTGRES_USER=eshop_user
      - POSTGRES_PASSWORD=eshop_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eshop_user -d eshop"]
      interval: 10s
      timeout: 5s
      retries: 5

  erp-api:
    image: williamyeh/json-server
    ports:
      - "3200:3200"
    volumes:
      - ./json-server-db.erp-api.json:/data/db.json
    command: ["--port", "3200", "--watch", "/data/db.json"]

  tax-api:
    image: williamyeh/json-server
    ports:
      - "3201:3201"
    volumes:
      - ./json-server-db.tax-api.json:/data/db.json
    command: ["--port", "3201", "--watch", "/data/db.json"]

volumes:
  postgres-data:

