version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=eshop
      - POSTGRES_USER=eshop_user
      - POSTGRES_PASSWORD=eshop_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eshop_user -d eshop"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - eshop-network

  erp-api:
    image: williamyeh/json-server
    ports:
      - "3200:3200"
    command: ["--port", "3200", "--watch", "/data/db.json"]
    volumes:
      - ./mock-apis/erp-api.json:/data/db.json
    networks:
      - eshop-network

  tax-api:
    image: williamyeh/json-server
    ports:
      - "3201:3201"
    volumes:
      - ./mock-apis/tax-api.json:/data/db.json
    command: ["--port", "3201", "--watch", "/data/db.json"]
    networks:
      - eshop-network

volumes:
  postgres-data:

networks:
  eshop-network:
    driver: bridge
